#ifndef __GFXINFO_H__
#define __GFXINFO_H__

typedef enum {
	TX_PLAY_CIRCLE,
	TX_PLAY_CIRCLEOVERLAY,
	TX_PLAY_CIRCLEAPPROACH,
	TX_PLAY_SPINNER,
	TX_PLAY_SPINNERBG,
	TX_PLAY_SPINNERBARS,
	TX_PLAY_SLIDERB0,
	TX_PLAY_SLIDERB1,
	TX_PLAY_SLIDERB2,
	TX_PLAY_SLIDERB3,
	TX_PLAY_SLIDERB4,
	TX_PLAY_SLIDERB5,
	TX_PLAY_SLIDERB6,
	TX_PLAY_SLIDERB7,
	TX_PLAY_SLIDERB8,
	TX_PLAY_SLIDERB9,
	TX_PLAY_DISC,
	TX_PLAY_SLIDERFOLLOW,
	TX_PLAY_SLIDERTICK,
	TX_PLAY_SLIDERREVERSE,
	
	TX_PLAY_HIT0,
	TX_PLAY_HIT50,
	TX_PLAY_HIT100,
	TX_PLAY_HIT100K,
	TX_PLAY_HIT300,
	TX_PLAY_HIT300K,
	TX_PLAY_HIT300G,
	TX_PLAY_SLIDER10,
	TX_PLAY_SLIDER30,
	
	TX_PLAY_SCOREBAR,
	TX_PLAY_SCOREBAR_BAR,
	TX_PLAY_SCOREBAR_KI,
	TX_PLAY_SCOREBAR_KIDANGER,
	TX_PLAY_SCOREBAR_KIDANGER2,
	
	TX_WHITE,

    TX_CURRENT_BG,

    // UI TEXTURES:
    TX_WELCOME_BG,
    TX_TAP_TO_START,
    TX_SONGSELECT_BG,
    TX_BUTTON_BIG,
    TX_BUTTON_MED,
    TX_BUTTON_SM,
    TX_BUTTON_SM_ACTIVE,
    TX_BUTTON_XS,
    TX_BUTTON_ARROW,
    TX_BEATMAP_ENTRY_BG,

    TX_BEATMAP_ENTRY_PIC_0,
    TX_BEATMAP_ENTRY_PIC_1,
    TX_BEATMAP_ENTRY_PIC_2,
    TX_BEATMAP_ENTRY_PIC_3
} TextureType;

#endif
